### ISSUE TITLE
Fertile Money Tree pattern disproved

### ISSUE THREAD

**Issue by drallieiv** [maael/nook#1]
Reverse engineering has disproved any pattern in Fertile money tree.
Fertile tree ratio is 30 - 70.
30% of cases (random) you get 3x what you planted (up to 99k x3)
70% of cases (random) you get 3x 10k if you planted at least 10k

You could gamble and get 99k x3, but the odds makes that average return only gets lower if you put more then 10k in the hole. You can ask Ninji to confirm

**Comment by maael** [comment]
Hey, thanks for the info!

Who's Ninji?

I don't suppose I could ask for a link to somewhere stating it's disproven so I can put it on the README please? I added the pattern tracking at the request of someone, so it'd be great to have something to point them to when they ask.

**Comment by drallieiv** [comment]
Ash Wolf, aka "Ninji" is one of the main dataminer who worked on decompiling ACNH 

Here is the main twitter topic :
https://twitter.com/_Ninji/status/1245206733062012928

and here is the aswer a bit later where he posted screenshots
https://twitter.com/_Ninji/status/1246436138778320896

He is using Ghidra which is an open source decompiler, but making the raw code readable and renaming things requires a lot of work.

**Comment by drallieiv** [comment]
The conclusion was also added to the fandom wiki
here; https://animalcrossing.fandom.com/wiki/Money_tree

Which is a source that tries to fact check a lot of thing, rather then just copying something their heard somewhere and do quick clickbait article or videos to get views, like some youtube channels or gaming blog do.

Datamining also proved and disproved many things.

**Comment by maael** [comment]
Hey, thanks for the information and the links!

I've added a note to the money tree tracker and a link to the money tree article on the wiki in e9405ca so people know, rather than just removing it.
