### ISSUE TITLE
Feature Request - i18n

### ISSUE THREAD

**Issue by drallieiv** [maael/nook#4]
Add localisation to the fish / bugs / fossil names for people playing the game in their own local instead of english.

**Comment by maael** [comment]
The basics of this has now been done in e225cd09d2597f95217cd46a53f057ae2b9bfe78 and the translations live here in [data/translations](https://github.com/maael/nook/tree/master/data/translations).

The translations are just a best effort from myself though, they are by no means perfect. I'd love PRs to fix any issues with them.

Here's what it looks like:

![Screenshot 2020-04-23 at 11 52 33](https://user-images.githubusercontent.com/5610674/80091394-f1e2a480-8558-11ea-8e5d-a547bb7d4b18.png)

There's now a flag next to the search, if you click on it it brings up this modal:

![Screenshot 2020-04-23 at 11 53 07](https://user-images.githubusercontent.com/5610674/80091441-03c44780-8559-11ea-8cb4-fd8200d31bbe.png)

That lets you select a language to view/search by.

At the moment it supports German, Spanish, French, Japanese, and English. It defaults to english, and will save your language choice on your device so it persists between refreshes.

With this I'll close this issue! Any future requests for new languages or fixes to translations can be their own thing.
